# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/input_code_request_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_code_reauest_dialog(object):
    def setupUi(self, input_code_reauest_dialog):
        input_code_reauest_dialog.setObjectName("input_code_reauest_dialog")
        input_code_reauest_dialog.resize(304, 174)
        self.verticalLayout = QtWidgets.QVBoxLayout(input_code_reauest_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.phone_edit = QtWidgets.QLineEdit(input_code_reauest_dialog)
        self.phone_edit.setObjectName("phone_edit")
        self.gridLayout.addWidget(self.phone_edit, 1, 0, 1, 1)
        self.send_code_button = QtWidgets.QPushButton(input_code_reauest_dialog)
        self.send_code_button.setObjectName("send_code_button")
        self.gridLayout.addWidget(self.send_code_button, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(input_code_reauest_dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(input_code_reauest_dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.code_edit = QtWidgets.QLineEdit(input_code_reauest_dialog)
        self.code_edit.setObjectName("code_edit")
        self.gridLayout.addWidget(self.code_edit, 3, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.accept_button = QtWidgets.QPushButton(input_code_reauest_dialog)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.cancel_button = QtWidgets.QPushButton(input_code_reauest_dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(input_code_reauest_dialog)
        QtCore.QMetaObject.connectSlotsByName(input_code_reauest_dialog)

    def retranslateUi(self, input_code_reauest_dialog):
        _translate = QtCore.QCoreApplication.translate
        input_code_reauest_dialog.setWindowTitle(_translate("input_code_reauest_dialog", "Dialog"))
        self.send_code_button.setText(_translate("input_code_reauest_dialog", "Отправить код"))
        self.label.setText(_translate("input_code_reauest_dialog", "Номер телефона"))
        self.label_2.setText(_translate("input_code_reauest_dialog", "Код из сообщения в Telegram"))
        self.accept_button.setText(_translate("input_code_reauest_dialog", "Принять"))
        self.cancel_button.setText(_translate("input_code_reauest_dialog", "Отмена"))
